# Use the OpenJDK 21 base image
FROM learningwithme/android:21.20-10-25

RUN apt update
# We directly answer the questions asked using the printf statement
RUN printf 'y\n1\n\1n' | apt install nodejs
RUN apt install -y npm
RUN npm -v 


# Set working directory
WORKDIR /workspace

# Default command
CMD ["bash"]