FROM amazoncorretto:11-alpine3.19

# Install Maven using apk (Alpine package manager)
RUN apk update && \
    apk add --no-cache maven bash

RUN java -version && mvn --version

# Set working directory
WORKDIR /workspace

# Default command
CMD ["bash"]